// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcWC_MuU9ntEuQDyVAA4fsaIrH96CDoTQ',
    appId: '1:586945630692:web:2031593514d0262ac377f1',
    messagingSenderId: '586945630692',
    projectId: 'fir-notification-fcbc6',
    authDomain: 'fir-notification-fcbc6.firebaseapp.com',
    storageBucket: 'fir-notification-fcbc6.appspot.com',
    measurementId: 'G-5732M27DX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOIwRYlicuHKMyVQMnlDeJra3wAfh9Ydk',
    appId: '1:586945630692:android:66caecdc6fc53d6bc377f1',
    messagingSenderId: '586945630692',
    projectId: 'fir-notification-fcbc6',
    storageBucket: 'fir-notification-fcbc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR_TTPwLObYldHlEBPWR6RZL0omFiqSjw',
    appId: '1:586945630692:ios:ad55a5156fb213abc377f1',
    messagingSenderId: '586945630692',
    projectId: 'fir-notification-fcbc6',
    storageBucket: 'fir-notification-fcbc6.appspot.com',
    androidClientId: '586945630692-q23bu8r460el63q6odeb7h45skusc4v3.apps.googleusercontent.com',
    iosClientId: '586945630692-cabg5nr9hjuj7im616s3g021r9ucmeu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR_TTPwLObYldHlEBPWR6RZL0omFiqSjw',
    appId: '1:586945630692:ios:ad55a5156fb213abc377f1',
    messagingSenderId: '586945630692',
    projectId: 'fir-notification-fcbc6',
    storageBucket: 'fir-notification-fcbc6.appspot.com',
    androidClientId: '586945630692-q23bu8r460el63q6odeb7h45skusc4v3.apps.googleusercontent.com',
    iosClientId: '586945630692-cabg5nr9hjuj7im616s3g021r9ucmeu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTask',
  );
}
